/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  numeric,
  integer,
  boolean,
  timestamp,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_menu_items_category = pgEnum("enum_menu_items_category", [
  "entradas-quentes",
  "entradas-frias",
  "saladas",
  "iguarias-do-mar",
  "peixes",
  "camaroes",
  "trattoria",
  "carnes-aves",
  "horta-ao-prato",
  "sobremesas",
  "bebidas",
  "drinks",
  "caipirinhas",
  "doses",
]);

export const menu_items = pgTable(
  "menu_items",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    name_en: varchar("name_en"),
    name_es: varchar("name_es"),
    category: enum_menu_items_category("category"),
    description: varchar("description"),
    description_en: varchar("description_en"),
    description_es: varchar("description_es"),
    price: numeric("price", { mode: "number" }),
    price_note: varchar("price_note"),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    featured: boolean("featured"),
    available: boolean("available").default(true),
    vegan: boolean("vegan"),
    lactose_free: boolean("lactose_free"),
    serves_two: boolean("serves_two"),
    sort_order: numeric("sort_order", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("menu_items_photo_idx").on(columns.photo),
    index("menu_items_updated_at_idx").on(columns.updatedAt),
    index("menu_items_created_at_idx").on(columns.createdAt),
  ],
);

export const posts = pgTable(
  "posts",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    cover: integer("cover_id").references(() => media.id, {
      onDelete: "set null",
    }),
    content: jsonb("content"),
    category: varchar("category"),
    published_at: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    published: boolean("published"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("posts_slug_idx").on(columns.slug),
    index("posts_cover_idx").on(columns.cover),
    index("posts_updated_at_idx").on(columns.updatedAt),
    index("posts_created_at_idx").on(columns.createdAt),
  ],
);

export const experiences = pgTable(
  "experiences",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    description: varchar("description"),
    background_image: integer("background_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    cta_label: varchar("cta_label"),
    sort_order: numeric("sort_order", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("experiences_background_image_idx").on(columns.background_image),
    index("experiences_updated_at_idx").on(columns.updatedAt),
    index("experiences_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_opening_hours = pgTable(
  "site_settings_opening_hours",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    days: varchar("days"),
    hours: varchar("hours"),
  },
  (columns) => [
    index("site_settings_opening_hours_order_idx").on(columns._order),
    index("site_settings_opening_hours_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_opening_hours_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    whatsapp: varchar("whatsapp"),
    phone: varchar("phone"),
    address: varchar("address"),
    instagram_url: varchar("instagram_url"),
    hero_video_url: varchar("hero_video_url"),
    google_maps_url: varchar("google_maps_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("site_settings_updated_at_idx").on(columns.updatedAt),
    index("site_settings_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const admins_sessions = pgTable(
  "admins_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("admins_sessions_order_idx").on(columns._order),
    index("admins_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [admins.id],
      name: "admins_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const admins = pgTable(
  "admins",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("admins_updated_at_idx").on(columns.updatedAt),
    index("admins_created_at_idx").on(columns.createdAt),
    uniqueIndex("admins_email_idx").on(columns.email),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "menu-itemsID": integer("menu_items_id"),
    postsID: integer("posts_id"),
    experiencesID: integer("experiences_id"),
    "site-settingsID": integer("site_settings_id"),
    mediaID: integer("media_id"),
    adminsID: integer("admins_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_menu_items_id_idx").on(
      columns["menu-itemsID"],
    ),
    index("payload_locked_documents_rels_posts_id_idx").on(columns.postsID),
    index("payload_locked_documents_rels_experiences_id_idx").on(
      columns.experiencesID,
    ),
    index("payload_locked_documents_rels_site_settings_id_idx").on(
      columns["site-settingsID"],
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_admins_id_idx").on(columns.adminsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["menu-itemsID"]],
      foreignColumns: [menu_items.id],
      name: "payload_locked_documents_rels_menu_items_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["postsID"]],
      foreignColumns: [posts.id],
      name: "payload_locked_documents_rels_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["experiencesID"]],
      foreignColumns: [experiences.id],
      name: "payload_locked_documents_rels_experiences_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["site-settingsID"]],
      foreignColumns: [site_settings.id],
      name: "payload_locked_documents_rels_site_settings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_locked_documents_rels_admins_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    adminsID: integer("admins_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_admins_id_idx").on(columns.adminsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_preferences_rels_admins_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_menu_items = relations(menu_items, ({ one }) => ({
  photo: one(media, {
    fields: [menu_items.photo],
    references: [media.id],
    relationName: "photo",
  }),
}));
export const relations_posts = relations(posts, ({ one }) => ({
  cover: one(media, {
    fields: [posts.cover],
    references: [media.id],
    relationName: "cover",
  }),
}));
export const relations_experiences = relations(experiences, ({ one }) => ({
  background_image: one(media, {
    fields: [experiences.background_image],
    references: [media.id],
    relationName: "background_image",
  }),
}));
export const relations_site_settings_opening_hours = relations(
  site_settings_opening_hours,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_opening_hours._parentID],
      references: [site_settings.id],
      relationName: "opening_hours",
    }),
  }),
);
export const relations_site_settings = relations(site_settings, ({ many }) => ({
  opening_hours: many(site_settings_opening_hours, {
    relationName: "opening_hours",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_admins_sessions = relations(
  admins_sessions,
  ({ one }) => ({
    _parentID: one(admins, {
      fields: [admins_sessions._parentID],
      references: [admins.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_admins = relations(admins, ({ many }) => ({
  sessions: many(admins_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    "menu-itemsID": one(menu_items, {
      fields: [payload_locked_documents_rels["menu-itemsID"]],
      references: [menu_items.id],
      relationName: "menu-items",
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: "posts",
    }),
    experiencesID: one(experiences, {
      fields: [payload_locked_documents_rels.experiencesID],
      references: [experiences.id],
      relationName: "experiences",
    }),
    "site-settingsID": one(site_settings, {
      fields: [payload_locked_documents_rels["site-settingsID"]],
      references: [site_settings.id],
      relationName: "site-settings",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    adminsID: one(admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_preferences_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_menu_items_category: typeof enum_menu_items_category;
  menu_items: typeof menu_items;
  posts: typeof posts;
  experiences: typeof experiences;
  site_settings_opening_hours: typeof site_settings_opening_hours;
  site_settings: typeof site_settings;
  media: typeof media;
  admins_sessions: typeof admins_sessions;
  admins: typeof admins;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_menu_items: typeof relations_menu_items;
  relations_posts: typeof relations_posts;
  relations_experiences: typeof relations_experiences;
  relations_site_settings_opening_hours: typeof relations_site_settings_opening_hours;
  relations_site_settings: typeof relations_site_settings;
  relations_media: typeof relations_media;
  relations_admins_sessions: typeof relations_admins_sessions;
  relations_admins: typeof relations_admins;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
