const ITEMS_2 = [
  // IGUARIAS DO MAR
  { name: 'Capitão Cabral',       category: 'iguarias-do-mar', description: 'Polvo à moda da casa com arroz cremoso de limão siciliano, pimentões e batata sauté.',                    price: 319, featured: true },
  { name: 'A Imperatriz',         category: 'iguarias-do-mar', description: 'Polvo à lagareiro com alho em lascas, batatas aos murros e arroz com brócolis.',                           price: 319 },
  { name: 'Paella do Porto',      category: 'iguarias-do-mar', description: 'Prato típico com arroz, marisco, lula, polvo e camarão.',                                                  price: 299 },
  { name: 'Sol Poente',           category: 'iguarias-do-mar', description: 'Fritada de frutos do mar, polvo, camarão, peixe e lula com molho de camarão.',                             price: 309 },
  { name: 'Tesouros do Mar',      category: 'iguarias-do-mar', description: '4 filés de lagosta, 4 camarões, 250g de congrio ou salmão, 4 bolinhos e 4 ostras gratinadas.',             price: 499, featured: true },
  { name: 'Ohana',                category: 'iguarias-do-mar', description: 'Salmão grelhado, 4 ostras gratinadas, 4 bolinhos, 4 camarões à romana e arroz cremoso.',                   price: 339 },
  { name: 'Lagosta Grelhada',     category: 'iguarias-do-mar', description: 'Grelhada na manteiga com batatas gratinadas e molho de camarão.',                                          price: 399 },
  { name: 'Lagosta a Fiorentina', category: 'iguarias-do-mar', description: 'Grelhada e gratinada com espinafre e bacon, guarnecida de batata palha.',                                  price: 399 },
  { name: 'Lagosta ao Champagne', category: 'iguarias-do-mar', description: 'Grelhada ao molho cremoso de espumante com batata sauté.',                                                 price: 399 },
  { name: 'Estrela do Mar',       category: 'iguarias-do-mar', description: 'Moqueca de peixe e camarão com farofa de dendê e batata sauté.',                                           price: 289 },
  { name: 'King Crab',            category: 'iguarias-do-mar', description: 'King crab inteiro e molhos especiais.',                                              price_note: '780/kg', featured: true },
  // PEIXES
  { name: 'Bacalhau às Natas',                    category: 'peixes', description: 'Bacalhau em lascas ao molho de nata. Arroz branco e batata palha.',                           price: 289 },
  { name: 'Bacalhau à Portuguesa',                category: 'peixes', description: 'Bacalhau confitado no azeite de oliva. Arroz branco e batata ao murro.',                      price: 289 },
  { name: 'Bacalhau na Crosta de Grão de Bico',   category: 'peixes', description: 'Com arroz branco, legumes e batatas gratinadas.',                                             price: 289 },
  { name: 'Congrio com Castanha e Banana',         category: 'peixes', description: 'Grelhado na cama de banana ao molho de castanha do Pará.',                                   price: 269 },
  { name: 'Peixe a Pomodoro',                     category: 'peixes', description: '4 enrolados de linguado com palmito ao molho pomodoro.',                                      price: 259 },
  { name: 'Belle Meunière — Congrio',              category: 'peixes', description: 'Grelhado com alcaparras, champignon e camarão.',                                             price: 269 },
  { name: 'Belle Meunière — Salmão / Linguado',   category: 'peixes', description: 'Grelhado com alcaparras, champignon e camarão.',                                             price: 259 },
  { name: 'Almirante do Porto — Congrio',          category: 'peixes', description: 'Com legumes, batata portuguesa, arroz com brócolis e molho de camarão.',                     price: 269 },
  { name: 'Almirante do Porto — Salmão / Linguado', category: 'peixes', description: 'Com legumes, batata portuguesa, arroz com brócolis e molho de camarão.',                   price: 259 },
  { name: 'Peixe à Fiorentina — Congrio',         category: 'peixes', description: 'Gratinado com espinafre e bacon. Arroz branco e batata palha.',                              price: 269 },
  { name: 'Peixe à Fiorentina — Salmão / Linguado', category: 'peixes', description: 'Gratinado com espinafre e bacon. Arroz branco e batata palha.',                            price: 259 },
  // CAMARÕES
  { name: 'Camarão Grelhado',     category: 'camaroes', description: 'Grelhados com batatas gratinadas e molho de camarão.',                                       price: 289 },
  { name: 'Camarão à Girassol',   category: 'camaroes', description: 'Com casca, arroz cremoso, bacon e batatas sauté.',                                           price: 289 },
  { name: 'Camarão à La Grega',   category: 'camaroes', description: 'Empanados com queijo prato, arroz à grega e batata frita.',                                  price: 289 },
  { name: 'Camarão a La Maragogi', category: 'camaroes', description: 'Cremoso com leite de coco, batata frita e legumes.',                                        price: 289 },
  { name: 'Camarão a La Cordazzo', category: 'camaroes', description: 'Grelhado ao molho de nata com rúcula, tomate seco e batata sauté.',                         price: 289 },
  { name: 'Camarão a Catupiry',   category: 'camaroes', description: 'Gratinado ao molho branco com catupiry e batata palha.',                                     price: 289 },
  { name: 'Pérola do Porto',      category: 'camaroes', description: 'Empanados com catupiry, arroz cremoso com limão, parmesão e crispy de alho poró.',           price: 289, featured: true },
  { name: 'Costa del Mar',        category: 'camaroes', description: '4 grelhados, 4 à grega, 4 à romana e 250g gratinados com batata frita.',                     price: 429, featured: true },
]
